checks:
    php: true
build:
  nodes:
    analysis:
      project_setup:
        override: true
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis
    tests-and-coverage:
tools:
  php_code_coverage: true
