checks:
    php: true
build:
  nodes:
    analysis:
      project_setup:
        override: true
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis
            coverage:
              file: tests/coverage.xml
              format: clover
